### ISSUE TITLE
Indication that the transcription is progressing 

### ISSUE THREAD

**Issue by abdcef** [GambitEngine/obsidian-transcription#2]
When using higher accuracy models, transcription takes time. Currently it’s not possible to know if it’s progressing. It will be great to have an indication that the plugin is running.

**Comment by michae1ho11ey** [comment]
I'd love to see this feature added. It was the first thing I wished for when I started using this plugin.
As for the implementation, I don't know what would be easy or possible to implement as I'm not a developer but here a few ideas of how to display that information (I saw that you requested implementation ideas in issue #1).

1. Put a progress status in the lower right hand corner in the status bar (not sure what it's called, it's where word count lives). Maybe a microphone icon then next to it a spinning progress icon with a percentages done or current status. 

2. Have a widget that exists in a sidebar widget with the progress status and any errors (when debug is enabled) or feedback listed under the progress. I'd love to see more visibility so I know if it's working or why it failed.

3. Display the status in the text body. Insert the text "Starting the transcription" when it starts, maybe every 30 seconds update the status with "Transcription still processing for ${time_since_start} seconds" and when it's done, replace the status with the transcribed text. If there is a failure or time out then update the status to something like "Transcription has failed due to ${error}". Putting some kind of dynamic element on the progress will help people recognize it's still working because if it stopped at 30 and after 5 minutes it is still 30 means the process crashed.

Out of the three options, I think option 1 is the slickest but not as easy to discover without people reading the plugin documentation. Putting the status in a sidebar widget doesn't feel like the typical use of such a widget but could provide a lot of easily accessible console logs as well. Displaying some status in the text is the easiest for a user to find and recognize that work is happening, but I'm not sure how easy it would be to update the body with ever changing data without destroying existing data.

Anyway, just my two cents. Great work so far. I'm excited for the other features you're working on.

**Comment by djmango** [comment]
Added in latest [dev build](https://github.com/GambitEngine/obsidian-transcription/actions/runs/4164160645) - now works on any device, including mobile, without installing third party tools - contact me via email or sign up at https://scribe.gambitengine.com/ for early access 🚀
